# Generated by Django 4.0.4 on 2022-06-03 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='canvas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.canvas'),
        ),
        migrations.AddField(
            model_name='combattracker',
            name='canvas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.canvas'),
        ),
        migrations.AddField(
            model_name='character',
            name='combattracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.combattracker'),
        ),
        migrations.AddField(
            model_name='canvas',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workspace'),
        ),
    ]
