# Generated by Django 4.0.4 on 2022-06-06 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='combattracker',
            new_name='combat_tracker',
        ),
    ]
