# Generated by Django 4.0.4 on 2022-06-06 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_combattracker_character_combat_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
