# Generated by Django 4.0.4 on 2022-08-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_character_created_character_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combattracker',
            name='round',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
