# Generated by Django 4.0.4 on 2022-08-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_combattracker_round_alter_note_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='conditions',
            field=models.CharField(blank=True, choices=[('GR', 'Grappled'), ('PA', 'Paralyzed'), ('RE', 'Restrained'), ('PR', 'Prone'), ('PO', 'Poisoned')], max_length=2),
        ),
        migrations.AlterField(
            model_name='character',
            name='statblock',
            field=models.BooleanField(default=False),
        ),
    ]
