# Generated by Django 4.0.4 on 2022-08-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_character_statblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='maxHitpoints',
            field=models.IntegerField(default=14),
            preserve_default=False,
        ),
    ]
