# Generated by Django 4.0.4 on 2022-08-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_character_maxhitpoints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='maxHitpoints',
            new_name='max_hitpoints',
        ),
    ]
