# Generated by Django 4.0.4 on 2022-08-24 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_maxhitpoints_character_max_hitpoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='conditions',
        ),
    ]
